@CCIMS.Web_HostAddress = https://localhost:8585
@PCS QR_HostAddress = https://localhost:34881

POST {{PCS QR_HostAddress}}/api/test/qrLink
Content-Type: application/json

{
  "ServicePartnerId": "SVPc6c396bd9e4546c7900c24f7fc00c009b60324e335e44e6a89fac833e346402c9b5a7c98f5d6472da937a817f570a88e1aa77fe4b64c4a91a3afd94510d79500",
  "Description": "Sample Description",

}

###

POST {{PCS QR_HostAddress}}/api/test/qrLink
Content-Type: application/json

{
  //QRCreationRequestDto
}
###

POST {{CCIMS.Web_HostAddress}}/api/sp/create
Content-Type: application/json

{
  "Name" : "Test SP1",
  "CompanyName" : "Test Company 1",
  "ContactNumber" : "Test Contact 1",
  "Email" : "Test Email 1",
  "ContactPerson" : "Test ContactPerson 1",
}

###

GET {{CCIMS.Web_HostAddress}}/api/qr?id=string

###

GET {{CCIMS.Web_HostAddress}}/api/qr?id=string

###

GET {{CCIMS.Web_HostAddress}}/api/qr?id=

###

POST {{CCIMS.Web_HostAddress}}/api/qr
Content-Type: application/json

{
  //QRCreationRequestDto
}

###

POST {{CCIMS.Web_HostAddress}}/api/qr
Content-Type: application/json

{
  "ServicePartnerId" : "SVP49f3962a5bff4306935e0936d5971fcaaae138a5739144bba11e92ae1072688717bfaae9d9044f369b048e9ef7a9ba9576aba2d790c44d67acb9806895317b35",
  "Description" : "asa"
}

###

GET {{CCIMS.Web_HostAddress}}/api/test/case/ref/generate

###

GET {{CCIMS.Web_HostAddress}}/api/test/case/ref/generate?x=3

###

@id=CSTb28badb18417489a8c7cd814d7860a4058ac78e5a0754c71ba98737031db21f6c75b9cf80d44449ab2a2b43fbbfb10833f168267f31f4a2aa1b67f66b65891c8
GET {{CCIMS.Web_HostAddress}}/api/customer?id={{id}}

###

@id=19
GET {{CCIMS.Web_HostAddress}}/api/cases?id={{id}}

###

@name=t
GET {{CCIMS.Web_HostAddress}}/api/fetch/sp?name={{name}}

###
